inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

RSpec/AnyInstance:
  Exclude:
    - 'spec/config/initializers/rack/attack_spec.rb'

RSpec/ExampleLength:
  Max: 10